name: ROS2 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ROS2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y python3-colcon-common-extensions
          sudo rosdep init || true
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build package
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --event-handlers console_cohesion+

      - name: Run tests
        run: |
          source /opt/ros/humble/setup.bash
          colcon test
          colcon test-result --verbose
