name: ROS2 CI ROS2のCI
# This workflow builds and tests a ROS2 package using GitHub Actions.
# このワークフローは、GitHub Actionsを使用してROS2パッケージをビルドおよびテストします。

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ROS2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y python3-colcon-common-extensions
          sudo - E rosdep init || true
          rosdep update
          rosdep install --from-paths . --ignore-src -r -y

      - name: Build package
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --event-handlers console_cohesion+

      # - name: Run tests
      #   run: |
      #     source /opt/ros/humble/setup.bash
      #     colcon test
      #     colcon test-result --verbose
